version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f pacman/docker/Dockerfile . | tee build.log
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:v1.0.0
      - echo List Docker images...
      - docker images
      - cat build.log
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest || { echo "Docker push failed"; exit 1; }
      - docker push $REPOSITORY_URI:v1.0.0
      version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f pacman/docker/Dockerfile . | tee build.log
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:v1.0.0
      - echo List Docker images...
      - docker images
      - cat build.log
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest || { echo "Docker push failed"; exit 1; }
      - docker push $REPOSITORY_URI:v1.0.0

  post_build:
    commands:
      - echo Deploying to Amazon EKS...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:latest
      - kubectl rollout status deployment/$DEPLOYMENT_NAME
      - echo Deployment complete!

