version: 0.2

phases:
  build:
    commands:
      - echo Building Docker image...
      - docker build -t pacman-game .
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker tag pacman-game:latest 851725642392.dkr.ecr.us-west-2.amazonaws.com/pacman-game:latest
      - docker push 851725642392.dkr.ecr.us-west-2.amazonaws.com/pacman-game:latest

artifacts:
  files:
    - '**/*'
