apiVersion: v1
kind: Service
metadata:
  name: pacman-headless-service
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None  # Headless service
  selector:
    app: pacman-game  # This should match the labels in the StatefulSet
