apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman-game
  template:
    metadata:
      labels:
        app: pacman-game
    spec:
      containers:
      - name: pacman-game
        image: 491085395701.dkr.ecr.us-west-2.amazonaws.com/my-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_SERVICE_HOST
          value: "mongodb"  # Name of the MongoDB service
        - name: MONGO_DATABASE
          value: "pacman"
        - name: MY_MONGO_PORT
          value: "27017"
        - name: MONGO_USE_SSL
          value: "false"
        - name: MONGO_VALIDATE_SSL
          value: "true" 
        - name: MONGO_AUTH_USER
          value: "idanu55"
        - name: MONGO_AUTH_PWD
          value: "E8by9sj9Bxz414SR"
